apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy

spec:
  replicas: 4
  template:
    metadata:
      name: pod-deploy
      labels: 
        app: 07Dec
    spec:
      containers:
        - name: pod-deploy-container 
          # image: jenkins/jenkins:lts
          image: nginx
  selector:
    matchLabels:
      app: 07Dec
