apiVersion: v1
kind: Service
metadata:
  name: demo-svc
spec:
  selector: 
    app: 07Dec
  type: NodePort
  ports:
    - port: 80   # service port
      targetPort: 8080 # container port Jenkins
      #targetPort: 80 # container port nginx
      nodePort: 30040  # Node port

